version: '3.1'
services:

    postgres:
        image: postgres:15.3-alpine
        restart: always
        ports:
            - "${DB_PORT}:${DB_PORT}"
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 1s
            timeout: 5s
            retries: 5

    api:
        build:
            context: ./server
            dockerfile: Dockerfile
        volumes:
            - /app/node_modules
            - ./server:/app
        env_file:
            - .env
        ports:
            - "${PORT}:${PORT}"
        depends_on:
            postgres:
                condition: service_healthy

    ui:
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - /app/node_modules
            - ./client:/app
        ports:
            - "5173:5173"
volumes:
    pgdata: