name: Lint

on:
  push:

jobs:
  eslint:
    name: Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install packages
        run: npm ci
        working-directory: server
      - name: Run ESLint
        run: npm run lint
        working-directory: server
